project:
  type: website
  output-dir: ./docs/

website:
  title: "Research"
  navbar:
    left:
      - text: "Germano Gallicchio"
        href: "https://germanogallicchio.github.io"

execute:
  echo: false

format: 
    revealjs:
        width: 1280     # slide width in pixels
        height: 720     # slide height in pixels
        margin: 0.01       # margin around slides (default is 0.1 = 10%)
        incremental: true
        center-title-slide: false
        center: false
        slide-number: true
        preview-links: false
        progress: true
        transition: fade
        theme: simple
        chalkboard: true
        scrollable: false
        touch: true
        controls: false
        vertical-sections: false
        audio-slideshow: true
        css: custom.css
    pdf:
        documentclass: scrartcl
        classoption:
          - DIV=11
          - numbers=noendperiod
        papersize: letter
        include-in-header:
          text: |
            \usepackage{tikz}

